### PR TITLE
Compatibility changes for new CMake

### PR DESCRIPTION
**Pull request by lobis**
Large lobis  [](https://gitlab.cern.ch/rest-for-physics/detectorlib/-/commits/lobis-geometry-info)

### CODE REVIEW

**Comment by jgalan** [comment]
If you want this to me reviewed, then add reviewers. If you still want to keep working on it and prevent merging, then change the status to draft.

**Comment by lobis** [comment]
It is ready for review @jgalan

**Comment by lobis** [comment]
This PR should close https://github.com/rest-for-physics/detectorlib/issues/4 since the new docker image in the pipeline uses latest Garfield.

**Comment by jgalan** [comment]
Please, make sure your updates are not behind master. You should merge master on your branch and push the changes here.

**Comment by lobis** [comment]
> Please, make sure your updates are not behind master. You should merge master on your branch and push the changes here.
> 
> I did so at [rest-for-physics/restG4#30](https://github.com/rest-for-physics/restG4/pull/30) and it broke the pipeline

done ^^

**Review by glorialuzon — APPROVED** [review]

**Pull request merged**
