### PR TITLE
Refactoring TRestDetectorReadout classes.

### PR DESCRIPTION
**Pull request by jgalan**
jgalan Large: 3331 [](https://github.com/rest-for-physics/detectorlib/commits/jgalan-refactoring)

Cherry-picking from PR https://github.com/rest-for-physics/detectorlib/pull/83 to find out the causes of pipeline failure

- [x] Adding readout validation that previously was in framework

### CODE REVIEW

**Comment by jgalan** [comment]
Any idea why alphaTrack Geant4 example would be failing in this PR? @juanangp @lobis

**Comment by lobis** [comment]
> Any idea why alphaTrack Geant4 example would be failing in this PR? @juanangp @lobis 

Ni idea sorry, I'll try to figure it out

**Comment by jgalan** [comment]
> > Any idea why alphaTrack Geant4 example would be failing in this PR? @juanangp @lobis
> 
> Ni idea sorry, I'll try to figure it out

Ok, I see now that the example is using a readout, so it is normal. It needs to be regenerated.

**Comment by jgalan** [comment]
HI @juanangp I have added a new validation job to `validation.yml`. But I don't see it in the jobs summary. Perhaps it will take effect only once this PR has been merged?

**Comment by juanangp** [comment]
> HI @juanangp I have added a new validation job to `validation.yml`. But I don't see it in the jobs summary. Perhaps it will take effect only once this PR has been merged?

You can change the pipeline in master to check if the pipeline suceed, this line https://github.com/rest-for-physics/framework/blob/2aae3c4346bc3914785b883438f278fc0668e358/.github/workflows/validation.yml#L645 to 
```
    uses: rest-for-physics/detectorlib/.github/workflows/validation.yml@jgalan-refactoring
```
This requires to make a new branch in `framework` and after is merged do not remove the `jgalan-refactoring` branch and later on  you should revert it to: 
```
    uses: rest-for-physics/detectorlib/.github/workflows/validation.yml@master
```
This is the only way that you can check if the pipeline is going to suceed, otherwise you can check after is merged, but it will not be tested in advance. We should implement submodule validation in framework in order to avoid this work around.

**Review by lobis — APPROVED** [review]

**Pull request merged**
