### PR TITLE
CMakeLists.txt adding a fix for old Garfield installation

### PR DESCRIPTION
**Pull request by jgalan**
jgalan  [](https://gitlab.cern.ch/rest-for-physics/detectorlib/-/commits/jgalan_garfield_fix)

This solves my problems. Perhaps there are even older Garfield installations that do not use the `include/Garfield` scheme?

### CODE REVIEW

**Comment by jgalan** [comment]
I place it as draft because there is an issue with RGL/EVE libraries linking

**Comment by juanangp** [comment]
Hi @jgalan 

This issue was pointed on #33 and is fixed in alphaAna branch, find below the dedicated commits:
https://github.com/rest-for-physics/framework/pull/124/commits/29ca94525a55ca3be61ddc430f69d602547cbae1
https://github.com/rest-for-physics/framework/pull/124/commits/0abfa409de883e5f07aed233b535bf06e1cc03a8
https://github.com/rest-for-physics/detectorlib/pull/33/commits/ae4d9d45385c3b7064af3f9f1f5d96433d14b0cd
https://github.com/rest-for-physics/detectorlib/pull/33/commits/5ed371337248e51503eab7aa1beea5cc2aaf8349

Today I have a chat with Luis and we agree on the latest commits. Anyhow, I don't know what is the best way to proceed, perhaps @lobis can comment more on that.

**Comment by jgalan** [comment]
Works awesome, so I remove it, just approve and we merge to master.

**Comment by juanangp** [comment]
Hi again,

I am missing commit https://github.com/rest-for-physics/detectorlib/commit/5ed371337248e51503eab7aa1beea5cc2aaf8349 although it has minor changes. On the other hand, I cannot see the PR with the commits in framework:
https://github.com/rest-for-physics/framework/commit/29ca94525a55ca3be61ddc430f69d602547cbae1
https://github.com/rest-for-physics/framework/commit/0abfa409de883e5f07aed233b535bf06e1cc03a8

**Comment by jgalan** [comment]
Right, you could cherry-pick it here. Anyway, it will be merged with the other PR.

I imagine, when we merge this PR to master, those commits will dissapear from your PR, so it is a way to clear it.

**Review by juanangp — APPROVED** [review]

**Pull request merged**
